import { groupBy } from "lodash-es"
import people from "./people"
import gql from 'graphql-tag'
import ApolloClient from 'apollo-boost';

const client = new ApolloClient({
    uri: 'https://api-useast.graphcms.com/v1/cjlwqnow603bo01gp1ub4hgoc/master'
})

import './style.scss'
import './image-example'

// const managerGroups = groupBy(people, "manager")

// const root = document.createElement("div")

// root.innerHTML = `<pre>${JSON.stringify(managerGroups, null, 2)}</pre>`
// document.body.appendChild(root)


var x = document.createElement("img")
x.setAttribute('id', 'generated by js')
document.body.appendChild(x)


client.query({
  query: gql`
    query cars {
      cars {
        id
        title
        price
        image {
            handle
        }
      }
    }
  `,
})
.then(data => o(data) )
.catch(error => console.error(error))

var o = (data) => {
  x.setAttribute('src', `https://media.graphcms.com/${data.data.cars[0].image.handle}` )
}